root: true
extends:
    - airbnb-typescript/base
parserOptions:
    project: ./tsconfig.json
rules:
    import/extensions: off
    import/prefer-default-export: off
    import/no-extraneous-dependencies: off
    class-methods-use-this: off
    eqeqeq: off
    no-param-reassign: off
